id: macd_bb_1
controller_name: macd_bb_v1
controller_type: directional_trading
total_amount_quote: '400'
manual_kill_switch: false
candles_config: []
connector_name: mexc
trading_pair: SUI-USDT
max_executors_per_side: 1
cooldown_time: 3600
leverage: 10
position_mode: HEDGE
stop_loss: '0.02'
take_profit: '0.15'
time_limit: 3600
take_profit_order_type: 1
trailing_stop:
  activation_price: '0.025'
  trailing_delta: '0.01'
candles_connector: mexc
candles_trading_pair: SUI-USDT
interval: 1m
bb_length: 200
bb_std: 2
bb_long_threshold: 0.2
bb_short_threshold: 0.95
macd_fast: 21
macd_slow: 42
macd_signal: 9
